### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by xyzchris0** [AlexisAhmed/Python3-NmapScanner#4]
Hey, Thanks for sharing the video and uploading the code. Just tried to run it and running into a traceback error with the udp on line 33 for option 2. "Keyerror: 'udp'". Is this something we need to import as well?

**Comment by AlexisAhmed** [comment]
Please follow the following steps:
1) Please ensure the script has executable permissions.
2) Ensure you have python-nmap installed
`pip install python-nmap`
3) Execute the script as root.

**Comment by xyzchris0** [comment]
Hey Thanks for the feedback. I am still running into the same issue. I ran the checks but will do some research on adding tcp into the code. When I ran the code without the elif for the first option it ran/returned fine on what was open. But when implementing the elif I then started getting errors for the tcp KeyError
